# Generated by Django 4.2.7 on 2023-11-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название сорта винограда')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место произрастания')),
                ('date', models.DateField(help_text='place', verbose_name='Время сбора')),
            ],
            options={
                'verbose_name': 'Сорт винограда',
                'verbose_name_plural': 'Сорта винограда',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='wine_sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вина')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('b_year', models.DurationField(help_text='в годах', verbose_name='Время выдержки в бочках')),
                ('bu_month', models.DurationField(help_text='в месяцах', verbose_name='Время выдержки в бутылках')),
                ('s_grape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wino.grape', verbose_name='Сорт винограда')),
            ],
            options={
                'verbose_name': 'Сорт вина',
                'verbose_name_plural': 'Сорта вин',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='bochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=50, verbose_name='')),
                ('date_izg', models.DateField(verbose_name='Дата изготовления')),
                ('obyem', models.FloatField(verbose_name='Объем')),
                ('pusto', models.BooleanField(verbose_name='Пустота')),
                ('data_zapolnenya', models.DateField(verbose_name='Дата заполнения бочки')),
                ('sort_vina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wino.wine_sort', verbose_name='Сорт вина')),
            ],
            options={
                'verbose_name': 'Бочка',
                'verbose_name_plural': 'Бочки',
                'ordering': ['-data_zapolnenya'],
            },
        ),
    ]
