# Generated by Django 4.2.7 on 2023-11-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grape',
            options={'ordering': ['-title'], 'verbose_name': 'Сорт винограда', 'verbose_name_plural': 'Сорта винограда'},
        ),
        migrations.AlterField(
            model_name='grape',
            name='place',
            field=models.CharField(blank=True, help_text='place', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grape',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
