# Generated by Django 4.2.7 on 2023-11-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0002_type_wine_remove_wine_sort_type_delete_bochka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=50, verbose_name='')),
                ('date_izg', models.DateField(verbose_name='Дата изготовления')),
                ('obyem', models.FloatField(verbose_name='Объем')),
                ('pusto', models.BooleanField(verbose_name='Пустота')),
                ('data_zapolnenya', models.DateField(verbose_name='Дата заполнения бочки')),
                ('sort_vina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wino.wine_sort', verbose_name='Сорт вина')),
            ],
            options={
                'verbose_name': 'Бочка',
                'verbose_name_plural': 'Бочки',
                'ordering': ['-data_zapolnenya'],
            },
        ),
    ]
