# Generated by Django 4.2.7 on 2023-11-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0002_alter_grape_options_alter_grape_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wine_sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='hfghfg')),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('b_year', models.DurationField()),
                ('bu_month', models.DurationField()),
                ('s_grape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wino.grape')),
            ],
            options={
                'verbose_name': 'Сорт вина',
                'verbose_name_plural': 'Сорта вин',
                'ordering': ['-title'],
            },
        ),
    ]
