# Generated by Django 4.2.7 on 2023-11-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0003_wine_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='bochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.CharField(max_length=50, verbose_name='hfghfg')),
                ('date_izg', models.DateField()),
                ('obyem', models.FloatField()),
                ('pusto', models.BooleanField()),
                ('data_zapolnenya', models.DateField()),
                ('sort_vina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wino.wine_sort')),
            ],
            options={
                'verbose_name': 'Бочка',
                'verbose_name_plural': 'Бочки',
                'ordering': ['-data_zapolnenya'],
            },
        ),
    ]
