# Generated by Django 4.2.7 on 2023-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0003_alter_bochka_date_izg_alter_bochka_mesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grape',
            name='date',
            field=models.CharField(choices=[('я', 'Январь '), ('ф', 'Февраль '), ('мт', 'Март '), ('ап', 'Апрель '), ('мй', 'Май '), ('ин', 'Июнь '), ('ил', 'Июль '), ('ав', 'Август '), ('с', 'Сентябрь '), ('о', 'Октябрь '), ('н', 'Ноябрь '), ('д', 'Декабрь ')], help_text='Введите время сбора урожая винограда', max_length=50, verbose_name='Время сбора'),
        ),
    ]
