# Generated by Django 4.2.7 on 2023-11-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0004_alter_grape_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bochka',
            name='data_zapolnenya',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заполнения бочки'),
        ),
        migrations.AlterField(
            model_name='bochka',
            name='obyem',
            field=models.FloatField(verbose_name='Объем в литрах'),
        ),
        migrations.AlterField(
            model_name='bochka',
            name='sort_vina',
            field=models.ForeignKey(blank=True, help_text='Выберите сорт вина', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wino.wine_sort', verbose_name='Сорт вина'),
        ),
    ]
