# Generated by Django 4.2.7 on 2023-11-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0005_alter_bochka_data_zapolnenya_alter_bochka_obyem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_sort',
            name='color',
            field=models.CharField(choices=[('Розовое', 'Розовое '), ('Красное', 'Красное '), ('Белое', 'Белое ')], max_length=50, verbose_name='Цвет'),
        ),
    ]
