# Generated by Django 4.2.7 on 2023-11-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0006_alter_wine_sort_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bochka',
            options={'verbose_name': 'Бочка', 'verbose_name_plural': 'Бочки'},
        ),
        migrations.AlterField(
            model_name='grape',
            name='date',
            field=models.CharField(choices=[('Январь', 'Январь '), ('Февраль', 'Февраль '), ('Март', 'Март '), ('Апрель', 'Апрель '), ('Май', 'Май '), ('Июнь', 'Июнь '), ('Июль', 'Июль '), ('Август', 'Август '), ('Сентябрь', 'Сентябрь '), ('Октябрь', 'Октябрь '), ('Ноябрь', 'Ноябрь '), ('Декабрь', 'Декабрь ')], help_text='Введите время сбора урожая винограда', max_length=50, verbose_name='Время сбора'),
        ),
    ]
