# Generated by Django 4.2.7 on 2023-11-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0007_alter_bochka_options_alter_grape_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bochka',
            options={'ordering': ['-pusto'], 'verbose_name': 'Бочка', 'verbose_name_plural': 'Бочки'},
        ),
        migrations.AlterModelOptions(
            name='wine_sort',
            options={'verbose_name': 'Сорт вина', 'verbose_name_plural': 'Сорта вин'},
        ),
    ]
