# Generated by Django 4.2.7 on 2023-11-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wino', '0008_alter_bochka_options_alter_wine_sort_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bochka',
            name='sort_vina',
            field=models.ForeignKey(blank=True, help_text='Выберите сорт вина', null=True, on_delete=django.db.models.deletion.CASCADE, to='wino.wine_sort', verbose_name='Сорт вина'),
        ),
        migrations.AlterField(
            model_name='wine_sort',
            name='s_grape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wino.grape', verbose_name='Сорт винограда'),
        ),
        migrations.AlterField(
            model_name='wine_sort',
            name='type1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wino.type_wine', verbose_name='Тип винограда'),
        ),
    ]
